max_harmonics: 2500
steps:
  ranges:
  - from: 1
    step: 1
    to: 10
    speed: 3.0
  - from: 10
    step: 5
    to: 50
    speed: 3.0
  - from: 50
    step: 10
    to: 100
    speed: 1.0
  - from: 100
    step: 100
    to: 500
    speed: 1.0
  - from: 500
    step: 500
    to: 5000
    speed: 1.0
show_contour: !Congruence
  modulo:
    3
  congruents:
    - 0
show_point: true
show_trace: Always
trace_length: 0.1
opacity: 0.8
show_nh: true
trace_width: 0.5
contour_width: 0.5
show_fourier_circles: !Congruence
  modulo:
    3
  congruents:
    - 1
    - 2
flip_y: true
