max_harmonics: 3
steps:
  ranges:
  - from: 1
    step: 1
    to: 5
    speed: 2.0
show_contour: Always
show_point: true
show_trace: Always
trace_length: 0.5
opacity: 0.5
show_nh: true
trace_width: 1.0
contour_width: 1.0
show_fourier_circles: Always
