max_harmonics: 500
steps:
  ranges:
  - from: 1
    step: 1
    to: 10
    speed: 3.0
  - from: 20
    step: 20
    to: 100
    speed: 1.0
  - from: 100
    step: 100
    to: 1000
    speed: 1.0
  - from: 1000
    step: 1000
    to: 10000
    speed: 1.0
show_contour: !Congruence
  modulo: 10
  congruents:
  - 8
  - 9
show_point: true
show_trace: Always
trace_length: 0.6
opacity: 0.7
show_nh: true
trace_width: 0.4
contour_width: 0.5
show_fourier_circles: !Congruence
  modulo: 2
  congruents:
  - 0
