num_points: 1000
speed: 3.0
steps:
  thresholds:
  - start: 10
    step: 1
  - start: 20
    step: 10
  - start: 100
    step: 10
  - start: 1000
    step: 100
  max_harmonic: 10000
show_contour: !OnceEvery
  modulo: 3
  remainders:
  - 0
show_point: true
show_trace: Always
trace_length: 0.5
opacity: 0.5
show_nh: true
trace_width: 0.1
contour_width: 0.5
show_fourier_circles: !OnceEvery
  modulo: 2
  remainders:
  - 0
